# Generated by Django 3.1.4 on 2021-04-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('case_number', models.CharField(max_length=100)),
                ('creation_date', models.DateTimeField()),
                ('last_discussion', models.DateTimeField()),
                ('prosecutor', models.CharField(max_length=100)),
                ('defendant', models.CharField(max_length=100)),
                ('defense', models.CharField(max_length=100)),
                ('case_description', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('upload_date', models.DateTimeField()),
                ('event', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('hour', models.TimeField()),
                ('category', models.CharField(max_length=100)),
                ('new_category', models.CharField(max_length=100)),
                ('case_description', models.CharField(max_length=1000)),
                ('tags', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='')),
                ('document', models.FileField(upload_to='')),
                ('case_number', models.PositiveIntegerField()),
            ],
        ),
    ]
