# Generated by Django 3.1.4 on 2021-05-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='path',
            field=models.CharField(default='C:\\Doc', max_length=500),
            preserve_default=False,
        ),
    ]
